//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTSP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CTSP()
        {
            this.CTTS = new HashSet<CTT>();
        }
    
        public string Thêm_ảnh { get; set; }
        public int Lượt_đánh_giá { get; set; }
        public string Mô_tả { get; set; }
        public string Màu { get; set; }
        public double Trả_góp { get; set; }
        public double Ưu_đãi { get; set; }
        public string Mã_CTTS { get; set; }
        public string Mã_SP { get; set; }
    
        public virtual SẢN_PHẨM SẢN_PHẨM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTT> CTTS { get; set; }
    }
}
