//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTT
    {
        public double Kích_thước { get; set; }
        public string Camera_sau { get; set; }
        public string Camera_trước { get; set; }
        public string Chip { get; set; }
        public int Ram { get; set; }
        public int Rom { get; set; }
        public int Pin { get; set; }
        public string OS { get; set; }
        public string Độ_phân_giải { get; set; }
        public string Mã_CTTS { get; set; }
    
        public virtual CTSP CTSP { get; set; }
    }
}
