//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giỏ_hàng
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Giỏ_hàng()
        {
            this.CTGHs = new HashSet<CTGH>();
            this.Hỏi_đáp = new HashSet<Hỏi_đáp>();
        }
    
        public string Mã_giỏ { get; set; }
        public double Đơn_giá { get; set; }
        public int Số_lượng { get; set; }
        public double Tạm_tính { get; set; }
        public string Mã_KH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTGH> CTGHs { get; set; }
        public virtual Khách_hàng Khách_hàng { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hỏi_đáp> Hỏi_đáp { get; set; }
    }
}
