//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hỏi_đáp
    {
        public string Mã_hỏi_đáp { get; set; }
        public string Họ_tên { get; set; }
        public int Thời_gian { get; set; }
        public int Nội_dung { get; set; }
        public string Mã_giỏ { get; set; }
    
        public virtual Giỏ_hàng Giỏ_hàng { get; set; }
    }
}
