//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BanHangEntities : DbContext
    {
        public BanHangEntities()
            : base("name=BanHangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminUser> AdminUsers { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<CTGH> CTGHs { get; set; }
        public virtual DbSet<CTSP> CTSPs { get; set; }
        public virtual DbSet<Đơn_hàng> Đơn_hàng { get; set; }
        public virtual DbSet<Giỏ_hàng> Giỏ_hàng { get; set; }
        public virtual DbSet<Hỏi_đáp> Hỏi_đáp { get; set; }
        public virtual DbSet<Khách_hàng> Khách_hàng { get; set; }
        public virtual DbSet<SẢN_PHẨM> SẢN_PHẨM { get; set; }
        public virtual DbSet<THƯƠNG_HIỆU> THƯƠNG_HIỆU { get; set; }
        public virtual DbSet<CTT> CTTS { get; set; }
        public virtual DbSet<Nhận_tại_của_hàng> Nhận_tại_của_hàng { get; set; }
        public virtual DbSet<Nhận_tận_nơi> Nhận_tận_nơi { get; set; }
    }
}
