//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SẢN_PHẨM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SẢN_PHẨM()
        {
            this.Comments = new HashSet<Comment>();
            this.CTSPs = new HashSet<CTSP>();
        }
    
        public string Mã_SP { get; set; }
        public string Tên_SP { get; set; }
        public double Giảm_giá { get; set; }
        public string Ảnh { get; set; }
        public double Giá { get; set; }
        public double Giá_lên_đời { get; set; }
        public int Yêu_thích { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTSP> CTSPs { get; set; }
    }
}
