//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THƯƠNG_HIỆU
    {
        public string Mã_TH { get; set; }
        public string Tên_TH { get; set; }
        public string Mã_User { get; set; }
    
        public virtual AdminUser AdminUser { get; set; }
    }
}
