//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Đơn_hàng
    {
        public string Mã_đơn_hàng { get; set; }
        public System.DateTime Thời_gian { get; set; }
        public string Mã_nhận_hàng { get; set; }
    
        public virtual CTGH CTGH { get; set; }
    }
}
